name: pop
favicon: null
layout_spectrum: 0.11102267540991306
typography_spectrum: 0.6443591630086303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.20459175412543118
  lightness: 0.6498850353527814
  saturation: 0.16492125228978693
  rhythmicContrast: 0.7094095731154084
purpose: []
